# -*- coding: utf-8 -*-
"""pertemuan2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvfjGwzhkfSy-8k64FZE70EL4V9lsdse
"""

#latihan 1
import numpy as np

# membuat array
nilai_siswa = np.array([85, 55, 40, 90])

# mengakses data pada array
print(nilai_siswa[3])

#Latihan 2
print("Hello World!")
print("Nama saya Magaretha Corliss")
print("NIM saya 2023071031")

#Latihan 3
if 5 > 2:
    print("Five is greater than two!")

#Latihan 4
x = 5
y = "John"
print(x)
print(y)

#Latihan 5
x = 4
x = "Sally"
print(x)



#Latihan 6
mylist = [3,2,1]

getFirst = mylist[0]
getSecond = mylist[1]

print(getFirst)
print(getSecond)

#Latihan 7
mylist = [3,2,1]

getFirst = mylist[0]
getLast = mylist[2]

print(getFirst)
print(getLast)

#Latihan 8
mylist = [3, 2, 1]

getKali = 1
for num in mylist:
    getKali *= num

print(getKali)

#9
mylist = [1, 2, 3, 4, 5]

getBagi = 1
for num in mylist:
    getBagi /= num

print(getBagi)

#10
def getSum(numbers):
    return sum(numbers)

set1 = [10, 20, 30]
set2 = [5, 10, 15]

hasil = getSum(set1) / getSum(set2)
print(hasil)

#11
def getSum(numbers):
    return sum(numbers)

set1 = [10, 20, 30]
set2 = [5, 10, 15]

hasil = getSum(set1) - getSum(set2)
print(hasil)